# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
stage: dev

image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent

mfvaluation:
  mf_http_port_ext: 30025
  mf_http_port: 7002
  mf_name: mfvaluation

  
